language: ruby
sudo: false
rvm: 2.3.1
cache:
  bundler: true
  
before_script:
  - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Notifications, used by our Gitter channel
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/afadcd70024390da5167
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
